### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to Akeneo\Pim\ApiClient\Pagination\PageFactory::createPage() must be of the type array, null given

### ISSUE THREAD

**Issue by akosglue** [Agence-DnD/PIMGento-2-API#111]
### Environment and configuration
1. Magento CE 2.3.1
2. PHP 7.1
3. Pimgento API 100.2.4

### Steps to reproduce
1. install magento 2.3.1
2. install pimgento api 100.2.4
3. in magento admin: click on Stores -> Catalog -> Pimgento

### Expected result
1. config page of pimgento displayed

### Actual result
Fatal error: Uncaught TypeError: Argument 1 passed to Akeneo\Pim\ApiClient\Pagination\PageFactory::createPage() must be of the type array, null given, called in 
... vendor/akeneo/api-php-client/src/Api/ChannelApi.php on line 61 and defined in 
... vendor/akeneo/api-php-client/src/Pagination/PageFactory.php:30 

Stack trace: #0 ... vendor/akeneo/api-php-client/src/Api/ChannelApi.php(61): Akeneo\Pim\ApiClient\Pagination\PageFactory->createPage(NULL)
#1 ... vendor/akeneo/api-php-client/src/Api/ChannelApi.php(69): Akeneo\Pim\ApiClient\Api\ChannelApi->listPerPage(10, false, Array)
#2 ... vendor/agencednd/module-pimgento-2-api/Model/Source/Filters/Channel.php(76): Akeneo\Pim\ApiClient\Api\ChannelApi->all()
#3 ... vendor/agencednd/module-pimgento-2-api/Model/Source/Filters/Channel.php(48): Pimgento\Api\Model\Sourc in 
... vendor/akeneo/api-php-client/src/Pagination/PageFactory.php on line 30

**Comment by akosglue** [comment]
it was a wrong installation on my side, on a clean install it is not reproducible.
