### ISSUE TITLE
Pagination call http instead of https

### ISSUE THREAD

**Issue by max21** [Agence-DnD/PIMGento-2-API#121]
Hello,
When I tried to import attributes options with pimgento I have this issue : 

![Sélection_067](https://user-images.githubusercontent.com/6594752/56955526-fe990c00-6b41-11e9-8d9f-0c523a9b24b5.png)

And after I have dump the stack trace :

```
#0 /var/www/htdocs/vendor/akeneo/api-php-client/src/Client/HttpClient.php(46): Akeneo\Pim\ApiClient\Client\HttpExceptionHandler->transformResponseToException(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/htdocs/vendor/akeneo/api-php-client/src/Client/AuthenticatedHttpClient.php(72): Akeneo\Pim\ApiClient\Client\HttpClient->sendRequest('GET', 'http://akeneo...', Array, NULL)
#2 /var/www/htdocs/vendor/akeneo/api-php-client/src/Pagination/Page.php(138): Akeneo\Pim\ApiClient\Client\AuthenticatedHttpClient->sendRequest('GET', 'http://akeneo...', Array)
#3 /var/www/htdocs/vendor/akeneo/api-php-client/src/Pagination/Page.php(78): Akeneo\Pim\ApiClient\Pagination\Page->getPage('http://akeneo...')
#4 /var/www/htdocs/vendor/akeneo/api-php-client/src/Pagination/ResourceCursor.php(60): Akeneo\Pim\ApiClient\Pagination\Page->getNextPage()
#5 /var/www/htdocs/vendor/agencednd/module-pimgento-2-api/Job/Option.php(197): Akeneo\Pim\ApiClient\Pagination\ResourceCursor->next()
#6 /var/www/htdocs/vendor/agencednd/module-pimgento-2-api/Job/Import.php(378): Pimgento\Api\Job\Option->insertData()
#7 /var/www/htdocs/vendor/agencednd/module-pimgento-2-api/Controller/Adminhtml/Import/Run.php(96): Pimgento\Api\Job\Import->execute()
#8 /var/www/htdocs/vendor/magento/framework/App/Action/Action.php(107): Pimgento\Api\Controller\Adminhtml\Import\Run->execute()
#9 /var/www/htdocs/vendor/magento/module-backend/App/AbstractAction.php(235): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#10 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http))
#11 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Pimgento\Api\Controller\Adminhtml\Import\Run\Interceptor->___callParent('dispatch', Array)
#12 /var/www/htdocs/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Pimgento\Api\Controller\Adminhtml\Import\Run\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#13 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Pimgento\Api\Controller\Adminhtml\Import\Run\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#14 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Pimgento\Api\Controller\Adminhtml\Import\Run\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#15 /var/www/htdocs/generated/code/Pimgento/Api/Controller/Adminhtml/Import/Run/Interceptor.php(26): Pimgento\Api\Controller\Adminhtml\Import\Run\Interceptor->___callPlugins('dispatch', Array, NULL)
#16 /var/www/htdocs/vendor/magento/framework/App/FrontController.php(55): Pimgento\Api\Controller\Adminhtml\Import\Run\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#17 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#19 /var/www/htdocs/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#20 /var/www/htdocs/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#21 /var/www/htdocs/vendor/magento/framework/App/Http.php(136): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#22 /var/www/htdocs/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http->launch()
#23 /var/www/htdocs/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#24 {main}"
```
The problem is the requested url for pagination. The url is http forced but my akeneo application works in https.
However the url configured in backoffice is in https.

**Comment by Dnd-Gimix** [comment]
Hello,

As announced on July 25, the repository PIMGento 2 API will be closed by the end of next week. 
Please make sure to check the new connector "Akeneo Connector for Magento 2", available on the Akeneo Github at this address : https://github.com/akeneo/magento2-connector-community

We took note of your issue and we will make sure to provide a fix if necessary on the new version of the connector.

Thank you for your contribution on this repository, we hope to see you back on the new repository !

Have a good day.

Regards,
